[package]
name = "arduino-test"
version = "0.1.0"
edition = "2021"

[dependencies.arduino-hal]
git = "https://github.com/rahix/avr-hal"
rev = "1aacefb335517f85d0de858231e11055d9768cdf"
features = ["arduino-uno"]

[profile.release]
panic = "abort"
lto = true
