[build] # --target avr-atmega328p.json
target = "avr-atmega328p.json"

[unstable] # -Z build-std=core
build-std = ["core"]

[target.'cfg(target_arch = "avr")']
runner = "ravedude uno --baudrate 115200"
